# Generated by Django 4.1 on 2022-08-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('emergency_phone', models.CharField(blank=True, max_length=255)),
                ('relation', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('spouse_name', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(max_length=255)),
                ('present_address', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('nid', models.CharField(max_length=20)),
                ('tin', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='L_DAY_COUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=255)),
                ('total_days', models.IntegerField()),
                ('enjoying_days', models.IntegerField()),
                ('remaining_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.CharField(max_length=20)),
                ('paid', models.CharField(choices=[('p', 'Paid'), ('u', 'Unpaid')], max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('reliever', models.CharField(max_length=20)),
            ],
        ),
    ]
