# Generated by Django 4.1 on 2022-08-06 16:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default=builtins.id, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='l_day_count',
            name='id',
            field=models.CharField(default=builtins.id, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='id',
            field=models.CharField(default=builtins.id, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
